### ISSUE TITLE
It doesn't work on older server versions since 1.1...

### ISSUE THREAD

**Issue by 5kuper** [JadedMC/CommandBlocker#6]
...because of Adventure API update (tested on 1.16.5). It will be good to note that in the description.

**Comment by 5kuper** [comment]
Uhh. Since 1.1 the plugin just won't start, but in 1.0 there're also issues:
`Could not pass event PlayerCommandPreprocessEvent to CommandBlocker v1.0
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.miniMessage()'`

**Comment by firewolf8385** [comment]
What server software are you using? I am not able to replicate this issue, and according to bStats there are a number of other servers running the plugin on older server versions without issue.

And what is the error when it fails to load?

**Comment by 5kuper** [comment]
I use Purpur-1.16.5-1171. 

`Error occurred while enabling CommandBlocker v1.4 (Is it up to date?)
java.lang.NoSuchFieldError: Class net.kyori.adventure.identity.Identity does not have member field 'net.kyori.adventure.pointer.Pointer LOCALE'`

**Comment by firewolf8385** [comment]
Looks like a conflict between the included version of adventure and the one installed on the server. This should be fixed in 1.4.1, which I just published.

**Comment by 5kuper** [comment]
Yes, it's fixed. Thanks.
